string[][] olls = [["27",
"S, Sune, Swimming Left",
"OCLL, OLL",
"(U L U' R') (U L' U' R)",
"R U R' U R U2 R'",
"y' R' U2 R U R' U R",
"y L' U2 L U L' U L",
"y2 L U L' U L U2 L'",
"R U' L' U R' U' L",
"U2 r2 U R' U' L' U R U' r' (x')",
"y' U R U' L' U R' U' L"],

["26",
"-S, Antisune, Swimming Right",
"OCLL, OLL",
"(R' U L U') (R U L')",
"y2 R' U' R U' R' U2 R",
"y' R U2 R' U' R U' R'",
"y L U2 L' U' L U' L'",
"L' U' L U' L' U2 L",
"L' U R U' L U R'",
"y' L' U R U' L U R'",
"y' R U2 R' U2' R' F R2 U' R' U' R U R' F'"],

["21",
"H, Double Sune, Flip, Cross",
"OCLL, OLL",
"R U R' U R U' R' U R U2 R'",
"y R U2 R' U' R U R' U' R U' R'",
"y F (R U R' U')3 F'",
"y F (U R U' R')3 F'",
"y F' (L' U' L U)3 F",
"R' U' R U' R' U R U' R' U2 R",
"L U L' U L U' L' U L U2 L'",
"y L' U2 L U L' U' L U L' U L",
"y (R' U R U) (R' U R U') (R' U R U') R' U' R U2 R' U R",
"L' U2 M' (y) R U2 R U2 R' U2 (y') l"],

["22",
"Pi, Bruno, Wheel, T-shirt",
"OCLL, OLL",
"R U2 R2' U' R2 U' R2' U2 R",
"f (R U R' U') f' F (R U R' U') F'",
"y2 f' (L' U' L U) f F' (L' U' L U) F",
"y2 L' U2 L2 U L2 U L2 U2 L'",
"R U2 R2 U' R' U R U' R U' R' y M' U2 M",
"R' U L U' R U' L' U' L U' L'",
"y2 L U' R' U L' U R U R' U R",
"y2 L' U R U' L U' R' U' R U' R'",
"R U' L' U R' U L U L' U L",
"R U R' U R U2 R' y' R U R' U R U2 R'",
"R U R' U' R' F R2 U R' U' R U R' U' F'",
"(R' U L U' R U L') U2 (R' U L U' R U L')"],

["23",
"U, Headlights, Superman",
"OCLL, OLL",
"R2' D' R U2 R' D R U2 R",
"R' U2 R F U' R' U' R U F'",
"F R U' R' U R U R' U R U' R' F'",
"(y') R U R' U' (R U' R' U2) (R U' R' U2) R U R'",
"(R' U' R U') R' U2 R2 U (R' U R U2 R')",
"R' U L' U R U' L U2 R' U R",
"F (R U R' U') (R' F R F2) (L' U2 L)",
"L2 D L' U2 L D' L' U2 L'",
"l2 U' R D2 R' U R D2 R",
"l2' U' z' U R2 U' L U R2 z' L",
"(y2) R' F2 R U2 R U2 R' F2 R U2 R'",
"(y2) R2 D R' U2 R D' R' U2 R'",
"R2' B2 R F2' R' B2 R F2' R",
"(y2) R d' R' U R d R' (y) R' U2 R",
"(x) R' B2' (R U' R' U) B2' (U' R U)",
"(y2)R U R' U R U2 R2' U' R U' R' U2' R",
"(R U R' U')3 (R' F R F')3"],

["24",
"T, Chameleon, Shark, Hammerhead, Little Horse, Stingray",
"OCLL, OLL",
"L F R' F' L' F R F'",
"r U R' U' L' U R U' x'",
"r U R' U' r' F R F'",
"(y' x') R U R' D R U' R' D'",
"(y') F R U R' U' R U' R' U' R U R' F'",
"R U R2' U' R2 U' R2' U2' R U' R U' R'",
"(y') R U' R' (U2 R U R') (U2 R U R') (U R U' R')",
"(y x) D' R' U R D R' U' R x'",
"(y x) D L U' L' D' L U L' x'",
"(y x') U' R' D R U R' D' R x",
"(y2) R' F' L F R F' L' F",
"(y2) R' F' r U R U' r' F",
"(y2) l' U' L U R U' r' F",
"(y') l U l' F R B' R' F'",
"R U' R' F R U R' U' R' F' R2 U' R' U2 R U' R'",
"(y) R U R D R' U' R D' R2",
"(y') R' U' R' D' R U R' D R2"],

["25",
"L, Bowtie, Triple-Sune, Side-winder, Diagonals, Spaceship",
"OCLL, OLL",
"R U2 R' U' (R U R' U') (R U R' U') R U' R'",
"R U R' U (R U' R' U) (R U' R' U) R U2 R'",
"y2 R' F R B' R' F' R B",
"y2 F R' F' L F R F' L'",
"y F' L F R' F' L' F R",
"y' F' r U R' U' r' F R",
"y' x U R' U' L U R U' r'",
"R' F' L' F R F' L F",
"y R' U' (R U R' F') (R U R' U') (R' F R2)",
"y2 R U2' R D R' U2 R D' R2'",
"y2 F R' F' r U R U' r'",
"y2 l' U R D' R' U' R D x'",
"x' D R U R' D' R U' l'",
"x' U L' U' R U L U' l'",
"x' R' D R U' R' D' R U x",
"x R' U R D' R' U' R D x'",
"y2 x L U' L' D L U L' D' x'",
"l' U' L' U R U' L U x'",
"U r U R U' L' U R' U' x'",
"y2 L' R U R' U' L U R U' R'",
"F R B R' F' l U' l'",
"U R U2 R' L' U' L U' R U' R' L' U2 L",
"F R U' R' U' R U2 R' U' F'",
"y R U R' U' R' F R U R U' R' F'",
"y' R U (R U R' U') (R' F) (R2 U') (R' U' R U) (R' F') U' R'",
"x U R' U' r x' U R U' r'",
"y' R2 D R' U R D' R' U' R'",
"R2 D' R U' R' D R U R",
"(y') R2 D R' U R D' R' U' R'"],

["1",
"Runway, Blank",
"OLL",
"(R U2) (R2' F R F' U2') (R' F R F')",
"R U B' R B R2 U' R' F R F'",
"(y) S U F R2 U' R2 U' R2 U R2 f'",
"L' U2 L2 F' L' F U2 L F' L' F",
"(y) R U' R2 D' r U' r' D R2 U R'"],

["2",
"Zamboni",
"OLL",
"F (R U R' U') F' f (R U R' U') f'",
"F (R U R' U') S (R U R' U') f'",
"(y2) F' (L' U' L U) F f' (L' U' L U) f",
"(y) r U r' U2 r U2 R' U2 R U' r'",
"(y) l' U' l U2 l' U2 L U2 L' U l",
"(y2) F R' F' R U R2 B' R' B U' R'",
"(y2) (F R' F' R) U2 F R' F' R2 U2 R'"],

["3",
"Anti-Nazi, Anti-Mouse",
"OLL",
"(y) f (R U R' U') f' U' F (R U R' U') F'",
"(y2) r' R2 U R' U r U2 r' U R' r",
"(y2) M U l' U2 l U L' U L M'",
"(y2) r' R2 U R' U r U2 r' U M'",
"(M'U) (r'U2 r U) (R' U R2 r')"],

["4",
"Nazi, Mouse",
"OLL",
"f (R U R' U') f' U F (R U R' U') F'",
"R' U2 x R' U R U' y R' U' R' U R' F",
"(y) r' R U' r U2 r' U' R U' R2' r",
"(y) M U' r U2' r' U' R U' R' M'",
"l L2 U' L U' l' U2 l U' M'"],

["17",
"Slash, Diagonal",
"OLL",
"R U R' U (R' F R F') U2 (R' F R F')",
"f (R U R' U') y' r' (R U R' U') R' F R F'",
"F R' F' l R L' U R U' R' U' M'",
"F' R U2 r' U F2 U' r U2 R' F",
"(F' R U2 r' d) R2 U' F R2 f' R",
"(y2) (F R' F' R2 r' U) (R U' R' U' M')"],

["18",
"Crown",
"OLL",
"(y') r U R' U R U2 r2' U' R U' R' U2 r",
"(y) F R U R' d R' U2 R' F R F'",
"R U2 R2 F R F' U2 M' U R U' r'",
"l' U' r' U2 L U2 L' U2 r U l",
"(y2) (R' F R F') U2 (R' F R F') (U F' U F)",
"(y) (F R' F' R) U2 (F R' F' R)(U' R U' R')",
"(y) x (U R' U' R) B2 (U R' U' R)(B' R B' R') x'",
"(y2) (F R U' R' U' R U R' F') U' (F R U R' U' F')",
"(y') (M' U M U2 M' U M) U (f R U R' U' f')"],

["19",
"Bunny",
"OLL",
"r' R U R U R' U' r R2' F R F'",
"M U R U R' U' M' R' F R F'",
"M U R U R' U' r R2' F R F'",
"r' U2 R U R' U r2 U2' R' U' R U' r'",
"R' U2 F R U R' U' y' R2 U2 R B",
"(y2) M' U' R' U' R U r' R2 B' R' B",
"(y2) M' U L U L' U' l L2 B L B'"],

["31",
"Couch",
"OLL",
"(y2) R' U' F U R U' R' F' R",
"(y) (F R' F' R) (U R U R') (U' R U' R')",
"L' d' R d L U' L' B' L",
"S' L' U' L U L F' L' f",
"(y) x U R' U' l U R U R' U' R U' R'",
"L' U' B U L U' L' B' L",
"(y') (S R U R' U' Fw' U' F)",
"(y) M' U' L' U' L F U F' L' U l",
"(y2) (L' U' L U) (R U R' U') M' U' L' U2 R U' (x')"],

["32",
"Anti-Couch",
"OLL"],

"R U B' U' R' U R B R'",
"(y2) x' R U R' D R U' R U' R' U R' D' x",
"(y2) F U R U' F' r U R' U' r'",
"R U x' U' F' R' F R U R'",
"R d L' d' R' U R B R'",
"S R U R' U' R' F R f'",
"(y) x' U' R U l' U' R' U' R U R' U R",
"R U2 R' U' F' U F R U' R'",
"l F U' F' R' F R U l'",
"(y) M' U R U R' F' U' F R U' r'",
"(y2) L U F' U' L' U L F L'",
"(y2) (R U R' U') (L' U' L U) M' U R U2 L' U x'"],

["43",
"Anti-P",
"OLL",
"(y) R' U' F' U F R",
"f' L' U' L U f",
"B' U' R' U R B",
"(y2) F' U' L' U L F",
"(y2) U R U R' F' L' U' L F",
"(y2) R' U' F R' F' R U R",
"(y') R U l' U' r' U' r U x'"],

["44",
"P",
"OLL",
"f (R U R' U') f'",
"(y2) F U R U' R' F'",
"(y) R U y' L U' L' B'",
"(y) F U R' F R F' U' F'"],

["36",
"Sea-Mew, Wario, Anti-Moustache",
"OLL",
"R' U' R U' R' U R U R y R' F' R",
"R' U' R U' R' U R U R B' R' B",
"(y2) (L' U' L U') (L' U L U) (L F' L' F)",
"(R U R' U') y (L' U2' L U) y' (R U R')",
"(R U R' U' F') (U2' F U) (R U R')",
"R U' R' U' F (U R U' R') F' R U2 R'",
"(y2) (F R' F' R) U (R U R' U')2 R U' R'"],

["38",
"Mario, Moustache",
"OLL",
"(y2) (R U R' U) (R U' R' U') (R' F R F')",
"L U L' U L U' L' U' L' B L B'",
"(L' U' L U) y' (R U2 R' U') y (L' U' L)"],

["48",
"Breakneck",
"OLL",
"F (R U R' U') (R U R' U') F'",
"(y2) f U R U' R' U R U' R' f'",
"(y) r U2 R' U' R U' r' R' U' R U' R' U2 R",
"(y') r' U' R U' R' U2 r R U2 R' U' R U' R'"],

["47",
"Anti-Breakneck",
"OLL",
"F' (L' U' L U) (L' U' L U) F",
"(y') r U R' U R U2 r' R' U2 R U R' U R",
"R' U' x (R' U R U')2 x' U R"],

["53",
"Frying Pan",
"OLL",
"l' U' L U' L' U L U' L' U2 l",
"(y2) r' U' R U' R' U R U' R' U2 r",
"(y') r' U2 R U R' U' R U R' U r",
"(y') r U2 R' U' R U' r' R U2 R' U' R U' R'",
"r U R' U R U2 r' R U R' U R U2 R'",
"F R U R' U' F' R U R' U' R' F R F'"],

["54",
"Anti-Frying Pan",
"OLL",
"r U R' U R U' R' U R U2 r'",
"(y') r U2 R' U' R U R' U' R U' r'",
"(y2) l U L' U L U' L' U L U2 l'",
"(y2) r' U' R U' R' U2 r R' U' R U' R' U2 R",
"(y) r' U2 R U R' U r R' U2 R U R' U R",
"(y) f (R U R' U') (R U R' U') f' F (R U R' U') F'",
"(y') r U2 R' U' R U R' U' R U' r'"],

["49",
"Right back squeezy",
"OLL",
"R B' R2 F R2 B R2 F' R",
"l U' l2' U l2 U l2' U' l",
"(y2) r U' r2 U r2 U r2 U' r",
"(y2) R' F R' F' R2 d2 y' R' F R F'",
"(y2) r U2 R2' U' R2 U' r'R' U2 R",
"(y') x' U l' U2 R U2 l U2 R' U x",
"(y') R' U2 R U R' U R F R U R' U' F'"],

["50",
"Right front squeezy",
"OLL",
"(y2) R' F R2 B' R2 F' R2 B R'",
"(y2) (r U R U' r') (F R' U R U' R' F')",
"(y2) x' R' D R2 U' R2 D' R2 U R' x",
"r' U r2 U' r2' U' r2 U r'",
"R B' R B R2' U2 F R' F' R",
"(y2) l' U l2 U' l2 U' l2 U l'",
"r' U2 R2' U R2 U rR U2 R'",
"(y') (R U2 R' U' R U' R') (F R U R' U' F')",
"(y') F' R U2 R' U2 R' F2 R F'",
"(y) x' U' r U2 L' U2 r' U2 L U' x",
"(y') F R U' R' U' R U R' U R U' R' F'"],

["34",
"City (C and T)",
"OLL",
"(R U R' U') x D' R' U R E' z'",
"(y2) R' U' R U y' x' R U L' U' M'",
"R U R' U' y' r' U' R U M'",
"(R U R' U') B' l' U R d' D",
"(R U R' U') B' (R' F R F') B",
"R U R' d' l' U' L U r' R",
"R U R2 U' R' F R U R U' F'",
"(y2) F R U R' U' R' F' r U R U' r'",
"(y2) R U2 R' F R U R' U' F' U R U R'",
"(R U R' U') y l' U' L U M"],

["46",
"Seein' Headlights (C and headlights)",
"OLL",
"R' U' R' F R F' U R",
"R' U' l' U l F' U R",
"(y) F U F l' U' l U' F'",
"R U l U' R' U F' l'",
"(y2) L F U' R U R' F' L'"],

["33",
"Tying Shoelaces, Key",
"OLL",
"(R U R' U') (R' F R F')",
"(y2) (L' U' L U) (L F' L' F)",
"R' U' R U l U' R' U x",
"R U R' F' U' F R U' R'"],

["45",
"Suit up, T",
"OLL",
"F (R U R' U') F'",
"f' (U' L' U L) f",
"(y2) f (U R U' R') f'",
"(y2) F' (L' U' L U) F"],

["55",
"Highway, Freeway",
"OLL",
"(y) R' F (R U R U') R2 F' R2 U' R' (U R U R')",
"R U2 R2 U' R U' R' U2 F R F'",
"R' U2 R2 U R' U R U2 y l' U' l",
"r U2 R2 F R F' U2 r' F R F'",
"(y) F U' R2 D R' U2 R D' R2' U F'",
"(y) R' F R U R' F R U' R' F' R U M' U' M",
"L F' L' U' L F' L' U L F L' U' M' U M",
"(L F' L' U' L F' L' U L F L' U' L)(R' F R) L'",
"R d' R2 D R' U2 R D' R2 d R'",
"(y) r U2 R' U' R2 r' U R' U' r U' r'",
"(y) r U2 R' U' M (R U R' U') r U' r'",
"(y) (F R U R' U' F') R U2 R2 U' R2 U' R2 U2 R",
"(y) r U2 R' U' M (R U R' U') r U' r'",
"(y) F (R U R' U') S (R U R' U') S' (R U R' U') F'",
"R' U' (F R' F' R) F (U R U' R') F' R"],

["56",
"Streetlights, Dead Man",
"OLL",
"r U r' U R U' R' U R U' R' r U' r'",
"r' U' r U' R' U R U' R' U R r' U r",
"L F L' U R U' R' U R U' R' L F' L'",
"F R U R' U' R F' r U R' U' r'",
"r U r' U R U' R' M' U R U2 r'",
"F R U R' U' F' r U R' U' r' F R F'",
"l U l' (U L U' L')2 l U' l'"],

["51",
"Bottlecap, Ant",
"OLL",
"F U R U' R' U R U' R' F'",
"(y2) f R U R' U' R U R' U' f'",
"(y') R' U2 R U R' F R' F' R U R"],

["52",
"Rice Cooker",
"OLL",
"R' U' R U' R' d R' U R B",
"R U R' U R d' R U' R' F'",
"R' U' R U' R' U F' U F R",
"(y2) R' U' x U R' U' R U R' U' R x' U R",
"(R U R' U R U2 R') U (F U R U' R' F')",
"(y) (r U2 R' U' R U' r') (F R U R' U' F')",
"(y') F R U R' U F' U' F U' F'"],

["5",
"Right back wide antisune (RBWAS), Lefty Square",
"OLL",
"(r' U2) (R U R' U r)",
"(y2) R' F2 L F L' F R",
"(y2) l' U2 L U L' U l",
"(y) x' U' l2 U l F' l U"],

["6",
"Right front wide antisune (RFWAS), Righty Square",
"OLL",
"(y2) r U2 R' U' R U' r'",
"l U2 L' U' L U' l'"],

["39",
"Fung",
"OLL",
"L F' (L' U' L U) F U' L'",
"(y2) l U' l' U' R U B U' R'",
"(y2) f' L F L' U' L' U L S",
"(y2) R U R' F' U' F U R U2 R'",
"(y2) R B' R' U' R U B U' R'",
"(y2) x' R U' x R' U' R U x' U F' l'",
"(y2) F R U R' U' R U R' U' R U' R' U' R U R' F'"],

["40",
"Anti-Fung",
"OLL",
"R' F (R U R' U') F' U R",
"(y2) f R' F' R U R U' R' S'",
"(y2) L' B L U L' U' B' U L"],

["7",
"Lightning, Wide Sune",
"OLL",
"r U R' U R U2 r'",
"(y) B L F' L F L2 B'",
"F R' F' R U2 R U2 R'",
"L' U2 L U2 L F' L' F"],

["8",
"Left Wide Sune (LWS), Reverse Lightning",
"OLL",
"l' U' L U' L' U2 l",
"(y2) r' U' R U' R' U2 r",
"(y') B' R' F R' F' R2 B",
"R U2 R' U2 R' F R F'"],

["11",
"Downstairs",
"OLL",
"F' (L' U' L U) F y F (R U R' U') F'",
"R U' R' U' R U' R' U2 F' U F U' R U R'",
"(y) r U R' U R' F R F' R U2 r'",
"(y') r' R2 U R' U R U2 R' U M'"],

["12",
"Upstairs",
"OLL",
"F (R U R' U') F' U F (R U R' U') F'",
"(y) F R U R2 F R y' R2 U R U2 R'",
"(y') r R2' U' R U' R' U2 R U' R r'",
"(y') M' R' U' R U' R' U2 R U' M"],

["9",
"Kite",
"OLL",
"(y') (R U R' U') R' F R2 U R' U' F'",
"(y') R' U' R y r U' r' U r U r'",
"(y') R' U' R y' x' R U' R' F R U R' x",
"(y) L' U' L y l U' l' U l U l'",
"R' U' R U' R' U R' F R F' U R",
"(y2) R U2 R' M' U' R U' R' U M"],

["10",
"Anti-Kite",
"OLL",
"(y') R U R' y R' F R U' R' F' R",
"(y') R U R' y' r' U r U' r' U' r",
"(y') (R U R' U) (R' F R F') R U2 R'",
"(y') (R' U' R U) R B' R2 U' R U B",
"(R' M' U2) (R U R' U) (R U R r')"],

["35",
"Fish Salad",
"OLL",
"R U2 R2' F R F' R U2 R'",
"R U B' R B R2 U R U2 R'",
"U' M2 F' U2 F M U2 R U L' x'",
"U' S2 L U2 L' S' U2 B' U' F z'",
"(y') R' U2 (R l) U' R' U l' U2 R",
"(y) R2 D r' U r D' r' U' R' U M'",
"f (R U R' U') f' (R U R' U R U2 R')"],

["37",
"Mounted Fish, Untying Shoelaces",
"OLL",
"(y) F R U' R' U' R U R' F'",
"(y) R' F R F' U' F' U F",
"(y) R' F R F' y' U' R' U R",
"(y) F R' F' R U R U' R'",
"(y) M' U R U' r' d' L' U L",
"x' U' R U l' U' R' U R",
"l U' R' U y' R U R' U' z'",
"R B' R' B U B U' B'",
"R U R' F' U F R U' R'",
"(y') r2 D' r U' r' D r U r",
"(y2) M' U' L' U l y' U R U' R'"],

["13",
"Gun, Trigger",
"OLL",
"F U R U' R2 F' R U R U' R'",
"F U R U2 R' U' R U R' F'",
"r U' r' U' r U r' y' R' U R",
"(y2) x' R U' R' F' R U R' x y R' U R",
"(y2) f R U R2 U' R' U R U' f'",
"R U2 L' U' L U2 R' U' L F' L' F"],

["14",
"Anti-Gun, Anti-Trigger",
"OLL",
"R' F R U R' F' R y' R U' R'",
"l' U l U l' U' l y' R U' R'",
"(y') R' U' y' R' U R2 B R' U' R' U R",
"(y2) B' U' R' U R2 B R' U' R' U R",
"(y2) x' L' U L F L' U' L x y' L U' L'",
"(y2) r' U r U r' U' r y R U' R'",
"L' U2 R U R' U2 L U R' F R F'"],

["15",
"Squeegee",
"OLL",
"(y2) l' U' l (L' U' L U) l' U l",
"(y2) R' F' R L' U' L U R' F R",
"r' U' r R' U' R U r' U r"],

["16",
"Anti-Squeegee",
"OLL",
"(y2) r U r' (R U R' U') r U' r'",
"(y2) r U M U R' U' r U' r'",
"l U l' L U L' U' l U' l'"],

["29",
"Spotted Chameleon",
"OLL",
"M U (R U R' U') (R' F R F') M'",
"r2 D' r U r' D r2 U' r' U' r",
"(y) (R U R' U') (R U' R' F') U' (F R U R')",
"(y) R' U2 R2 U R' U' R' U2 F R F'",
"(y2) R' F R F' R U2 R' d' L' U' L",
"(y2) R' F R F' R U2 R' U' y' R' U' R",
"(y2) R2' U' R F R' U R2' U' R' F' R",
"(y2) r U2 R' U' R U' r' R' U2 R U R' U R",
"x' U' R' U L' U' R2 U' R' U2 r",
"(y') (R U R' U R U2 R') U (R U R' U') (R' F R F')"],

["30",
"Anti-Spotted Chameleon",
"OLL",
"r' U2 R U R' U r R U2 R' U' R U' R'",
"f R U R2 U' R' U R2 U' R' f'",
"R2' U R' B' R U' R2' U R B R'",
"M U' (L' U' L U) (L F' L' F) M'",
"l U' R' U l' U2 R d L U L'",
"R B' R' B R' U2 R U y R U R'",
"(y2) F U (R U2 R' U')2 F'",
"(y2) (L F' L' F) L' U2 L d (R U R')",
"(y2) F' L U L2 U L2 U2 L' U F",
"(y2) F R' F R2 U' R' U' R U R' F2",
"(y2) F U R U' x' U R' D' R U' l'",
"(y2) M' U' (R' U' R U) x' (R U' R' U) M x",
"(y2) M' U' (R' U' R U) l (U' R' U R) L'",
"(y') M' U R U' r' U2 R2 B' R' B R'",
"(y') (R' U' R U' R' U2 R) U' (R U R' U') (R' F R F')",
"(y2) r2 D r' U' r D' r2' U r U r'",
"(y') r' D' r U' r' D r2 U' r' U r U r'",
"(y2) r' D' r U r' D r U' r U R' U' M"],

["41",
"Awkward Fish, Dalmation",
"OLL",
"R U' R' U2 R U y R U' R' y' U' R'",
"(y) R U2' R' U' R U' R2 y L' U' L U F",
"(y2) F U R U' R' F' R' U2 R U R' U R",
"(y2) (R U R' U R U2 R') F (R U R' U') F'",
"(y2) r R2 y' R' U' R U y R U' M",
"(y2) R2 L z' l' U' R d L U' L l'",
"(y2) M' R' F' U' F U R U' M",
"R' M2 U' F' U F r U' M'",
"(y) (R B' R' B)2 R' U' R U R' U' R",
"(y') r U2 R' U' R U' r' U' R U R' U R U2 R'"],

["42",
"Lefty Awkward Fish, Anti-Dalmation",
"OLL",
"r' R2 y R U R' U' y' R' U M'",
"R' U' R U F R U R' U' R' U R U' F'",
"L' U L U2 L' U' y' L' U L U F",
"(y) R' U2 R U R' U R2 y R U R' U' F'",
"(y) (R' F R F')2 R U R' U' R U R'",
"(y2) L2 R' z r U L' d' R' U R' r",
"(y2) M' U f U R U' R' f' M",
"(M R) (f R f') (U' R' U M')",
"(M U) (F R U R' U' F') M'",
"(R' U' R U' R' U2 R) F (R U R' U') F'",
"All Corners Oriented"],

["28",
"Stealth, Arrow, Arrowhead, Fish",
"OLL",
"r U R' U' r' R U R U' R'",
"(y) r U2 R' U' R U' r' R U R' U R U2 R'",
"r U R' U R U2 r' R U2 R' U' R U' R'",
"(y) r' U' R U' R' U2 r R' U2 R U R' U R",
"(y') r' U' R U M' U' R' U R",
"r' U2 R U R' U r R' U' R U' R' U2 R",
"F R U R' U' F' U2 F R U R' U' F'",
"F R U R' U' F2 L' U' L U F",
"M U M' U2 M U M'",
"(y) M U' M' U2 M U' M'",
"U2 M' U M U2 M' U M",
"(y') M U M2 U M' U2 M U M",
"M U M U M' U' M U' M U M",
"M U M' U M U2 M' U' M U' M'",
"(y) M U' M U' M' U M U M U' M",
"(y2) M U' M2 U' M' U2 M U' M",
"(y') M U M' U M U M' U M U M'",
"(y') M' U' M U M U M U' M U' M' U M2",
"(y') M2 U M' U2 M U M U M U2 M' U M",
"(y2) M' U M U' M U' M U M U M' U' M2",
"M U' M2 U2 M' U' M U2 M U' M U' M'",
"(y') M' U' F2 M2 U' M U F2 U M2",
"(y2) M' U F2 M2 U M U' F2 U' M2",
"R' F R S R' F' R S'",
"L2 S U' S' U L2 U S U S'",
"(y) L F' L' S' L F L'S",
"(y') M U R U R' U' M' U R U' R'",
"R2 F2 L F L' F2 R F' R"],

["57",
"Mummy, H, I, Brick",
"OLL",
"R U R' U' M' U R U' r'",
"M' U' M' U' M' d2 M' U' M' U' M'",
"M' U M' U M' d2 M' U M' U M'",
"R U R' U' r R' U R U' r'",
"x' M' U' R U M U' R' U x",
"R' U' R U M U' R' U r",
"M U M U M U2 M' U M' U M'",
"M' U M' U M' U M' U2 M' U M' U M' U M'",
"M' U' M' U' M' U2 M U' M U' M",
"M U M' U' M U M' U M U2 M'",
"M' U' M U M' U' M U' M' U2 M",
"M U M2 U2 M U M U2 M U' M' U' M'",
"M' U' M2 U2 M' U' M' U2 M' U M U M",
"M2 U' M U M' U M' U' M' U' M' U M",
"M2 U' M' U M U M U' M U' M U M'",
"(y) M' U M' U M' U M' U M' U' M' U' M' U' M'",
"(y) M' U M U M' U M U' M' U' M",
"(y) M' U' M U' M' U' M U M' U M",
"(y) M U' M' U' M U' M' U M U M'",
"(y) M U M' U M U M' U' M U' M'",
"M U M' U' B2 M U M' U' B2",
"M' U' M U F2 M' U' M U F2",
"M2 U' F2 U' M' U M2 F2 U M",
"F M' F U M2 U2 M2 U F' M F'"],

["20",
"X, Checkers",
"OLL",
"r' R U R U R' U' r2 R2' U R U' r'",
"M U R U R' U' M2 U R U' r'",
"r U R' U' M2 (U R U' R') U' M'",
"x U R' U' M2 U R U' M' x' U' M'",
"M' U2 M' U2 M' U M U2 M U2 M",
"M' U2 M U2 M' U M U2 M' U2 M",
"M U2 M' U2 M U M' U2 M U2 M' U'",
"M d r2 U M' U2 M U r2 S'",
"M U M F R' F' M2 F R F' U'",
"R2 U2 R' F2 U2 R2 F' R2 U2 F2 R U2 R2 U'",
"R B U B' R' F2 B D' L' D B' F2",
"L' R' F' U2 L2 U2 L2 U2 L2 F L R",
"F2 M F2 M2 U' M2 F2 M' F2 U",
"F2 M F2 U' M2 U B2 M B2",
"F' B' R E S R S' R2 E' F B",
"S' U' S2 U R' U' R' S' R U R",
"(M U)4 (M' U)4",
"(M' U)3 M' U' (M' U)3 M'",
"(M' U)4 y2 (M' U)4",]
]